# Generated by Django 4.0.1 on 2022-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=13, verbose_name='Названия турнира')),
                ('description', models.TextField(max_length=200, verbose_name='Описание турнира')),
                ('geo', models.CharField(max_length=50, verbose_name='Геолокация')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.CharField(max_length=8, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Турниры',
                'verbose_name_plural': 'Турнир',
            },
        ),
    ]
