# Generated by Django 4.0.1 on 2022-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaitingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=40, verbose_name='Весовая категория')),
                ('champion', models.CharField(max_length=30, verbose_name='Имя чемпиона')),
                ('image', models.ImageField(upload_to='images')),
                ('one_fighter', models.CharField(max_length=30, verbose_name='Первое место рейтинга')),
                ('two_fighter', models.CharField(max_length=30, verbose_name='Второе место рейтинга')),
                ('three_fighter', models.CharField(max_length=30, verbose_name='Третье место рейтинга')),
                ('four_fighter', models.CharField(max_length=30, verbose_name='Четвертое место рейтинга')),
                ('five_fighter', models.CharField(max_length=30, verbose_name='Пятое место рейтинга')),
            ],
        ),
    ]
