# Generated by Django 4.0.1 on 2022-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_raitingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpost',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
