# Generated by Django 4.0.1 on 2022-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tourpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Кличка бойца')),
                ('name', models.CharField(max_length=30, verbose_name='Имя и Фамилия')),
                ('typing', models.PositiveSmallIntegerField(choices=[(1, 'Легкий вес'), (1, 'Средний вес'), (1, 'Полутяжелый вес')], verbose_name='Тип')),
                ('stats', models.CharField(max_length=10, verbose_name='Рекорд (В-П-Н)')),
                ('image', models.ImageField(upload_to='images')),
                ('geo', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('years', models.CharField(max_length=2, verbose_name='Возраст')),
                ('weight', models.CharField(max_length=3, verbose_name='Вес')),
                ('arms', models.CharField(max_length=3, verbose_name='Длина рук')),
                ('growth', models.CharField(max_length=3, verbose_name='Рост')),
            ],
            options={
                'verbose_name': 'Карточки бойцов',
                'verbose_name_plural': 'Карточки бойцов',
            },
        ),
        migrations.AlterModelOptions(
            name='raitingmodel',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
    ]
