# Generated by Django 4.0.1 on 2022-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fightermodel_alter_raitingmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightermodel',
            name='typing',
            field=models.PositiveSmallIntegerField(choices=[('Легкий вес', 'Легкий вес'), ('Средний вес', 'Средний вес'), ('Полутяжёлый вес', 'Полутяжелый вес')], verbose_name='Тип'),
        ),
    ]
