# Generated by Django 4.0.1 on 2022-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_fightermodel_typing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightermodel',
            name='typing',
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='type',
            field=models.CharField(default=1, max_length=12, verbose_name='Весовая - Легкий/Средний/Полутяжелый. Строго по форме'),
            preserve_default=False,
        ),
    ]
