# Generated by Django 4.0.1 on 2022-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_fightermodel_typing_fightermodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightermodel',
            name='type',
        ),
        migrations.AddField(
            model_name='fightermodel',
            name='typing',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Легкий вес'), (2, 'Средний вес'), (3, 'Полутяжелый вес')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
