# Generated by Django 4.0.1 on 2022-06-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_fightermodel_type_fightermodel_typing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightermodel',
            name='typing',
            field=models.PositiveSmallIntegerField(choices=[('Легкий вес', 1), ('Средний вес', 2), ('Полутяжелый вес', 3)], verbose_name='Тип'),
        ),
    ]
