# Generated by Django 4.0.1 on 2022-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_fightermodel_type_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightermodel',
            name='link',
            field=models.CharField(default=1, max_length=120, verbose_name='Ссылка на W-cloud'),
            preserve_default=False,
        ),
    ]
