# Generated by Django 4.0.1 on 2022-06-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_fightermodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fight', models.CharField(choices=[('warning', 'Ничья'), ('success', 'Победа'), ('secondary', 'В разработке')], max_length=20, verbose_name='Статус боя')),
                ('status_fight', models.CharField(max_length=25, verbose_name='Статус - НИЧЬЯ/ В РАЗРАБОТКЕ/ ПОБЕДА P1 ИЛИ P2')),
                ('name_1', models.CharField(max_length=30, verbose_name='Имя первого бойца')),
                ('name_2', models.CharField(max_length=30, verbose_name='Имя второго бойца')),
                ('result', models.CharField(max_length=8, verbose_name='Результат боя, если нет. То прочерк')),
                ('type_education', models.CharField(choices=[('Лёгкий', 'light'), ('Средний', 'middle'), ('Полутяжёлый', 'heavywight')], max_length=20, verbose_name='Весовая')),
            ],
            options={
                'verbose_name': 'Статистика боёв',
                'verbose_name_plural': 'Статистика боёв',
            },
        ),
    ]
