# Generated by Django 4.0.1 on 2022-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_statisticsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsmodel',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
