# Generated by Django 4.0.1 on 2022-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_statisticsmodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFighterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('social', models.CharField(max_length=120, verbose_name='Связь с вами')),
                ('description', models.TextField(max_length=2500, verbose_name='О вашем, опыте в боях, краткая биография.')),
                ('weight_category', models.CharField(choices=[('Лёгкий', 'light'), ('Средний', 'middle'), ('Полутяжёлый', 'heavywight')], max_length=20, verbose_name='Весовая')),
                ('type_education', models.CharField(choices=[('Одобрена', 'success'), ('Отклонена', 'danger')], default='На проверке', max_length=20, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявки в промоушен',
                'verbose_name_plural': 'Заявки в промоушен',
            },
        ),
    ]
